
CREATE DATABASE 'SkateSpotWebsite';

use 'SkateSpotWebsite';

CREATE TABLE 'Users' (
	'Id' INT UNSINGED NOT NULL AUTO_INCREMENT,
	'Username' VARCHAR(20),
	'Password' VARCHAR(20)
);

CREATE TABLE 'Spots' (
	'Id' INT UNSINGED NOT NULL AUTO_INCREMENT,
	'Latitude' FLOAT,
	'Longitude' FLOAT
);

CREATE TABLE 'Comments' (
	'Id' INT UNSINGED NOT NULL AUTO_INCREMENT,
	'UserId' INT UNSINGED NOT NULL,
	'SpotId' INT UNSINGED NOT NULL,
	'IsReply' BOOL,
	'ReplyId' INT UNSINGED NOT NULL,
	'Text' VARCHAR(500),
	'AttachmentType' VARCHAR(5), ---PHOTO, VIDEO, or NONE
	'UpVotes' INT UNSIGNED,
	'DownVotes' INT UNSIGNED
);

